version: 2
updates:
  - package-ecosystem: docker
    directory: /.buildkite
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 2
