version: 2

release:
  name_template: Test Splitter v{{.Version}}
  draft: true
  replace_existing_draft: true
  prerelease: auto
  make_latest: false
  mode: replace

archives:
  - format: binary

builds:
  - env:
      - CGO_ENABLED=0
    goos: [linux, darwin]
    goarch: [amd64, arm64]
    ldflags: "-X 'main.Version={{ .Version }}'"
