version: 2

release:
  name_template: Test Engine Client v{{.Version}}
  draft: false
  prerelease: auto
  make_latest: false
  mode: replace

changelog:
  use: github-native
  
archives:
  - format: binary

builds:
  - env:
      - CGO_ENABLED=0
    goos: [linux, darwin]
    goarch: [amd64, arm64]
    ldflags: "-X 'main.Version=v{{ .Version }}'"

brews:
  - name: test-splitter
    description: "Buildkite test engine client"
    homepage: "https://github.com/buildkite/test-splitter"
    skip_upload: auto
    directory: .
    test: |
      version_output = shell_output("test-splitter --version")
      assert_match "v#{version}\n", version_output
    repository:
      owner: buildkite
      name: homebrew-buildkite
      branch: master

git:
  ignore_tags:
    - '{{ envOrDefault "GORELEASER_IGNORE_TAG" ""}}'

dockers:
  - image_templates:
      - "packages.buildkite.com/buildkite/test-splitter-docker/test-splitter:v{{ .Version }}-amd64"
    dockerfile: "packaging/Dockerfile"
    build_flag_templates:
      - "--platform=linux/amd64"
  - image_templates:
      - "packages.buildkite.com/buildkite/test-splitter-docker/test-splitter:v{{ .Version }}-arm64"
    goarch: arm64
    dockerfile: "packaging/Dockerfile"
    build_flag_templates:
      - "--platform=linux/arm64"
  - image_templates:
      - "buildkite/test-splitter:v{{ .Version }}-amd64"
    # skip pushing image to Dockerhub if it's a prerelease
    skip_push: auto
    dockerfile: "packaging/Dockerfile"
    build_flag_templates:
      - "--platform=linux/amd64"
  - image_templates:
      - "buildkite/test-splitter:v{{ .Version }}-arm64"
    # skip pushing image to Dockerhub if it's a prerelease
    skip_push: auto
    goarch: arm64
    dockerfile: "packaging/Dockerfile"
    build_flag_templates:
      - "--platform=linux/arm64"
docker_manifests:
  - name_template: "packages.buildkite.com/buildkite/test-splitter-docker/test-splitter:v{{ .Version }}"
    image_templates:
      - "packages.buildkite.com/buildkite/test-splitter-docker/test-splitter:v{{ .Version }}-amd64"
      - "packages.buildkite.com/buildkite/test-splitter-docker/test-splitter:v{{ .Version }}-arm64" 
  - name_template: "packages.buildkite.com/buildkite/test-splitter-docker/test-splitter:latest"
    image_templates:
      - "packages.buildkite.com/buildkite/test-splitter-docker/test-splitter:v{{ .Version }}-amd64"
      - "packages.buildkite.com/buildkite/test-splitter-docker/test-splitter:v{{ .Version }}-arm64"
  - name_template: "buildkite/test-splitter:v{{ .Version }}"
    image_templates:
      - "buildkite/test-splitter:v{{ .Version }}-amd64"
      - "buildkite/test-splitter:v{{ .Version }}-arm64"
    # skip pushing manifest to Dockerhub if it's a prerelease
    skip_push: auto
  - name_template: "buildkite/test-splitter:latest"
    image_templates:
      - "buildkite/test-splitter:v{{ .Version }}-amd64"
      - "buildkite/test-splitter:v{{ .Version }}-arm64"
    # skip pushing manifest to Dockerhub if it's a prerelease
    skip_push: auto

nfpms:
  - vendor: Buildkite
    id: linux-pkg
    homepage: https://github.com/buildkite/test-splitter
    maintainer: Buildkite <support@buildkite.com>
    description: Buildkite test engine client
    license: MIT
    formats:
      - deb
      - rpm
    provides:
      - test-splitter

publishers:
  - name: buildkite-packages
    disable: "{{if .Prerelease}}true{{end}}"
    cmd: .buildkite/steps/upload-linux-packages.sh {{ .ArtifactPath }}
    ids:
      - linux-pkg
    env:
      - BUILDKITE_JOB_ID={{ .Env.BUILDKITE_JOB_ID }}
      - BUILDKITE_AGENT_ACCESS_TOKEN={{ .Env.BUILDKITE_AGENT_ACCESS_TOKEN }}
