version: 2
project_name: test-engine-client

release:
  name_template: Test Engine Client v{{.Version}}
  draft: false
  prerelease: auto
  make_latest: "{{not .Prerelease}}"
  mode: replace

changelog:
  use: github-native
  
archives:
  - format: binary

builds:
  - env:
      - CGO_ENABLED=0
    goos: [linux, darwin]
    goarch: [amd64, arm64]
    ldflags: "-X 'github.com/buildkite/test-engine-client/internal/version.Version=v{{ .Version }}'"
    binary: bktec

checksum:
  name_template: "bktec_{{ .Version }}_checksums.txt"

brews:
  - name: bktec
    description: "Buildkite Test Engine Client"
    homepage: "https://github.com/buildkite/test-engine-client"
    skip_upload: auto
    directory: Formula
    test: |
      version_output = shell_output("bktec --version")
      assert_match "v#{version}\n", version_output
    repository:
      owner: buildkite
      name: homebrew-buildkite
      branch: master

git:
  ignore_tags:
    - '{{ envOrDefault "GORELEASER_IGNORE_TAG" ""}}'

dockers:
  - image_templates:
      - "packages.buildkite.com/buildkite/test-engine-client-docker/test-engine-client:v{{ .Version }}-amd64"
    dockerfile: "packaging/Dockerfile"
    build_flag_templates:
      - "--platform=linux/amd64"
  - image_templates:
      - "packages.buildkite.com/buildkite/test-engine-client-docker/test-engine-client:v{{ .Version }}-arm64"
    goarch: arm64
    dockerfile: "packaging/Dockerfile"
    build_flag_templates:
      - "--platform=linux/arm64"
  - image_templates:
      - "buildkite/test-engine-client:v{{ .Version }}-amd64"
    # skip pushing image to Dockerhub if it's a prerelease
    skip_push: auto
    dockerfile: "packaging/Dockerfile"
    build_flag_templates:
      - "--platform=linux/amd64"
  - image_templates:
      - "buildkite/test-engine-client:v{{ .Version }}-arm64"
    # skip pushing image to Dockerhub if it's a prerelease
    skip_push: auto
    goarch: arm64
    dockerfile: "packaging/Dockerfile"
    build_flag_templates:
      - "--platform=linux/arm64"
  - image_templates:
      - "public.ecr.aws/buildkite/test-engine-client:v{{ .Version }}-amd64"
    # skip pushing image to AWS ECR if it's a prerelease
    skip_push: auto
    dockerfile: "packaging/Dockerfile"
    build_flag_templates:
      - "--platform=linux/amd64"
  - image_templates:
      - "public.ecr.aws/buildkite/test-engine-client:v{{ .Version }}-arm64"
    # skip pushing image to AWS ECR if it's a prerelease
    skip_push: auto
    goarch: arm64
    dockerfile: "packaging/Dockerfile"
    build_flag_templates:
      - "--platform=linux/arm64"
docker_manifests:
  - name_template: "packages.buildkite.com/buildkite/test-engine-client-docker/test-engine-client:v{{ .Version }}"
    image_templates:
      - "packages.buildkite.com/buildkite/test-engine-client-docker/test-engine-client:v{{ .Version }}-amd64"
      - "packages.buildkite.com/buildkite/test-engine-client-docker/test-engine-client:v{{ .Version }}-arm64" 
  - name_template: "packages.buildkite.com/buildkite/test-engine-client-docker/test-engine-client:latest"
    image_templates:
      - "packages.buildkite.com/buildkite/test-engine-client-docker/test-engine-client:v{{ .Version }}-amd64"
      - "packages.buildkite.com/buildkite/test-engine-client-docker/test-engine-client:v{{ .Version }}-arm64"
  - name_template: "buildkite/test-engine-client:v{{ .Version }}"
    image_templates:
      - "buildkite/test-engine-client:v{{ .Version }}-amd64"
      - "buildkite/test-engine-client:v{{ .Version }}-arm64"
    # skip pushing manifest to Dockerhub if it's a prerelease
    skip_push: auto
  - name_template: "buildkite/test-engine-client:latest"
    image_templates:
      - "buildkite/test-engine-client:v{{ .Version }}-amd64"
      - "buildkite/test-engine-client:v{{ .Version }}-arm64"
    # skip pushing manifest to Dockerhub if it's a prerelease
    skip_push: auto
  - name_template: "public.ecr.aws/buildkite/test-engine-client:v{{ .Version }}"
    image_templates:
      - "public.ecr.aws/buildkite/test-engine-client:v{{ .Version }}-amd64"
      - "public.ecr.aws/buildkite/test-engine-client:v{{ .Version }}-arm64"
    # skip pushing manifest to AWS ECR if it's a prerelease
    skip_push: auto
  - name_template: "public.ecr.aws/buildkite/test-engine-client:latest"
    image_templates:
      - "public.ecr.aws/buildkite/test-engine-client:v{{ .Version }}-amd64"
      - "public.ecr.aws/buildkite/test-engine-client:v{{ .Version }}-arm64"
    # skip pushing manifest to AWS ECR if it's a prerelease
    skip_push: auto

nfpms:
  - vendor: Buildkite
    id: linux-pkg
    package_name: bktec
    homepage: https://github.com/buildkite/test-engine-client
    maintainer: Buildkite <support@buildkite.com>
    description: Buildkite Test Engine Client
    license: MIT
    formats:
      - deb
      - rpm
    provides:
      - bktec

publishers:
  - name: buildkite-packages
    disable: "{{if .Prerelease}}true{{end}}"
    cmd: .buildkite/steps/upload-linux-packages.sh {{ .ArtifactPath }}
    ids:
      - linux-pkg
    env:
      - BUILDKITE_JOB_ID={{ .Env.BUILDKITE_JOB_ID }}
      - BUILDKITE_AGENT_ACCESS_TOKEN={{ .Env.BUILDKITE_AGENT_ACCESS_TOKEN }}
      - BUILDKITE_AGENT_JOB_API_SOCKET={{ .Env.BUILDKITE_AGENT_JOB_API_SOCKET }}
      - BUILDKITE_AGENT_JOB_API_TOKEN={{ .Env.BUILDKITE_AGENT_JOB_API_TOKEN }}
