// bktec fetches and runs test plans generated by Buildkite
// Test Engine.
package main

import (
	"context"
	"errors"
	"fmt"
	"os"
	"os/exec"

	"github.com/buildkite/test-engine-client/internal/command"
	"github.com/buildkite/test-engine-client/internal/version"
	"github.com/urfave/cli/v3"
)

func main() {
	cmd := &cli.Command{
		Name:   "bktec",
		Usage:  "Buildkite Test Engine Client",
		Action: command.Run,
		Flags: []cli.Flag{
			&cli.StringFlag{
				Name:  "files",
				Value: "",
				Usage: "override the default test file discovery by providing a path to a file containing a list of test files (one per line)",
			},
			&cli.BoolFlag{
				Name:   "version",
				Value:  false,
				Usage:  "print version information and exit",
				Action: printVersion,
			},
		},
		Commands: []*cli.Command{
			{
				Name:   "run",
				Usage:  "Run tests (default)",
				Action: command.Run,
				Flags: []cli.Flag{
					&cli.StringFlag{
						Name:  "plan-identifier",
						Value: "",
						Usage: "run the tests from a plan previously generated matching the provided plan-identifier",
					},
				},
			},
			{
				Name:   "plan",
				Usage:  "Generate test plan without running tests",
				Action: command.Plan,
				Flags: []cli.Flag{
					&cli.IntFlag{
						Name:  "max-parallelism",
						Value: 0,
						Usage: "instruct the test planner to calculate optimal parallelism for the build, not to exceed the provided value. When 0 this flag is ignored and the test plan parallelism will be derived from the BUILDKITE_PARALLEL_JOB_COUNT environment variable",
						Action: func(ctx context.Context, cmd *cli.Command, v int) error {
							if v < 0 || v > 1000 {
								return fmt.Errorf("max-parallelism must be between 0 and 1000")
							}
							return nil
						},
					},
				},
			},
		},
	}

	if err := cmd.Run(context.Background(), os.Args); err != nil {
		logErrorAndExit(err)
	}
}

func printVersion(ctx context.Context, cmd *cli.Command, versionFlag bool) error {
	// Flag will be true if called with `bktec [...] --version`
	if !versionFlag {
		return nil
	}
	fmt.Printf("bktec %s\n", version.Version)
	os.Exit(0)
	return nil
}

func logErrorAndExit(err error) {
	fmt.Fprintln(os.Stderr, err)

	exitError := new(exec.ExitError)
	if errors.As(err, &exitError) {
		// If error wraps an exitError exit with the specified code ...
		os.Exit(exitError.ExitCode())
	} else {
		// otherwise exit code 16
		os.Exit(16)
	}
}
