FROM ruby:3.3.6-slim-bookworm AS ruby
FROM cypress/included:13.16.0 AS cypress

FROM public.ecr.aws/docker/library/golang:1.23.3 AS golang

COPY --from=ruby / /
COPY --from=cypress / /

RUN gem install rspec
RUN yarn global add jest
