steps:
  - name: ":go::robot_face: Check Code Committed"
    key: check-code-committed
    command: .buildkite/steps/check-code-committed.sh
    plugins:
      - docker-compose#v4.14.0:
          config: .buildkite/docker-compose.yml
          cli-version: 2
          run: build

  - name: ":go: Tests with race detector"
    key: tests
    command: ".buildkite/steps/tests.sh -race"
    artifact_paths: cover.{html,out}
    plugins:
      - docker-compose#v4.14.0:
          config: .buildkite/docker-compose.yml
          cli-version: 2
          run: build
      - test-collector#v1.2.0:
          files: "junit-*.xml"
          format: "junit"

  - wait

  - group: ":hammer_and_wrench: Binary builds"
    steps:
    - name: ":{{matrix.os}}: Build {{matrix.os}} {{matrix.arch}} binary"
      command: ".buildkite/steps/build-binary.sh {{matrix.os}} {{matrix.arch}}"
      key: build-binary
      artifact_paths: "pkg/*"
      plugins:
        docker-compose#v4.14.0:
          config: .buildkite/docker-compose.yml
          cli-version: 2
          run: build
      matrix:
        setup:
          os:
            - darwin
            - linux
          arch:
            - amd64
            - arm64
  
  - trigger: buildkite-splitter
    key: e2e-tests
    label: ":bonezone: End-to-end Tests"
    # branches: "main"
    depends_on: 
      - build-binary
    build:
      message: "End-to-end test for Test Splitter Build #${BUILDKITE_BUILD_NUMBER}"
      branch: "${BUILDKITE_BRANCH}"

  - name: ":pipeline: Upload Release Pipeline"
    command: ".buildkite/steps/upload-release-step.sh"
    depends_on: 
      - build-binary
      - e2e-tests
    branches: "main"
