steps:
  - name: ":cook: Prepare release"
    plugins:
      - docker#v5.13.0:
          image: ghcr.io/caarlos0/svu:v2.1.0
          entrypoint: ""
          command: [".buildkite/steps/prepare-release.sh"]
          mount-buildkite-agent: true

  - wait

  - name: ":rocket: Release"
    artifact_paths: "dist/**/*"
    plugins:
      # IAM role to access SSM
      - aws-assume-role-with-web-identity#v1.4.0:
          role-arn: arn:aws:iam::445615400570:role/pipeline-buildkite-test-engine-client-release
          session-tags:
            - organization_slug
            - organization_id
            - pipeline_slug
      - aws-ssm#v1.0.0:
          parameters:
            GITHUB_TOKEN: /pipelines/buildkite/test-engine-client-release/GH_TOKEN
            DOCKERHUB_USER: /pipelines/buildkite/test-engine-client-release/dockerhub-user
            DOCKERHUB_PASSWORD: /pipelines/buildkite/test-engine-client-release/dockerhub-password
      # IAM role to access ECR
      - aws-assume-role-with-web-identity#v1.4.0:
          role-arn: arn:aws:iam::172840064832:role/pipeline-buildkite-test-engine-client-release
          credential-name-prefix: ECR_
          session-tags:
            - organization_slug
            - organization_id
            - pipeline_slug
      - docker-compose#v5.12.0:
          config: .buildkite/docker-compose.yml
          run: release
          command: ["/bin/sh", ".buildkite/steps/release.sh"]
          mount-buildkite-agent: true
          mount-checkout: true
          volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
          environment:
            - GITHUB_TOKEN
            - DOCKERHUB_USER
            - DOCKERHUB_PASSWORD
            - ECR_AWS_ACCESS_KEY_ID
            - ECR_AWS_SECRET_ACCESS_KEY
            - ECR_AWS_SESSION_TOKEN
