env:
  AWS_DEFAULT_REGION: us-east-1

steps:
  - name: ":golangci-lint: Lint"
    plugins:
      - docker#v5.11.0:
          image: golangci/golangci-lint:v1.64.8
          workdir: /go/src/github.com/your-org/your-repo
          command:
            - golangci-lint
            - run

  - name: ":go: Tests"
    command: ".buildkite/steps/tests.sh"
    parallelism: 2
    artifact_paths:
      - cover.{html,out}
      - internal/api/pacts/*
    plugins:
      - aws-assume-role-with-web-identity:
          role-arn: arn:aws:iam::445615400570:role/pipeline-buildkite-test-engine-client
      - aws-ssm#v1.0.0:
          parameters:
            BUILDKITE_TEST_ENGINE_SUITE_TOKEN: /pipelines/buildkite/test-engine-client/SUITE_TOKEN
            BUILDKITE_TEST_ENGINE_API_ACCESS_TOKEN: /pipelines/buildkite/test-engine-client/API_ACCESS_TOKEN
      - docker-compose#v4.14.0:
          config: .buildkite/docker-compose.yml
          cli-version: 2
          run: ci
          propagate-environment: true
          environment:
            - BUILDKITE_TEST_ENGINE_SUITE_TOKEN
            - BUILDKITE_TEST_ENGINE_API_ACCESS_TOKEN
      - test-collector#v1.11.0:
          files: "junit-*.xml"
          format: "junit"
          # This is to prevent the test runner as part of our test fixture trigger test collection
          # such as pytest + python test collector
          api-token-env-name: "BUILDKITE_TEST_ENGINE_SUITE_TOKEN"

  - wait

  - group: ":hammer_and_wrench: Build binaries"
    steps:
    - name: ":{{matrix.os}}: Build {{matrix.os}} {{matrix.arch}} binary"
      artifact_paths: "dist/**/*"
      plugins:
        docker#v5.11.0:
          image: goreleaser/goreleaser:v2.8.1
          mount-buildkite-agent: true
          environment:
            - GOOS={{matrix.os}}
            - GOARCH={{matrix.arch}}
          command:
            - build
            - --single-target
            - --snapshot
      matrix:
        setup:
          os:
            - darwin
            - linux
          arch:
            - amd64
            - arm64
