steps:
  - name: ":go::robot_face: Check Code Committed"
    command: .buildkite/steps/check-code-committed.sh
    plugins:
      - docker-compose#v4.14.0:
          config: .buildkite/docker-compose.yml
          cli-version: 2
          run: build

  - name: ":go: Tests with race detector"
    command: ".buildkite/steps/tests.sh -race"
    artifact_paths:
      - cover.{html,out}
      - internal/api/pacts/*
    plugins:
      - docker-compose#v4.14.0:
          config: .buildkite/docker-compose.yml
          cli-version: 2
          run: build

  - wait

  - group: ":hammer_and_wrench: Build binaries"
    steps:
    - name: ":{{matrix.os}}: Build {{matrix.os}} {{matrix.arch}} binary"
      artifact_paths: "dist/**/*"
      plugins:
        docker#v5.11.0:
          image: goreleaser/goreleaser:v2.1.0
          mount-buildkite-agent: true
          environment:
            - GOOS={{matrix.os}}
            - GOARCH={{matrix.arch}}
          command:
            - build
            - --single-target
            - --snapshot
      matrix:
        setup:
          os:
            - darwin
            - linux
          arch:
            - amd64
            - arm64
