steps:
  - name: ":octocat: :rocket: Create Github Release"
    command: ".buildkite/steps/github-release.sh"
    plugins:
      - aws-assume-role-with-web-identity:
          role-arn: arn:aws:iam::445615400570:role/pipeline-buildkite-test-splitter-client-release
      - aws-ssm#v1.0.0:
          parameters:
            GH_TOKEN: /pipelines/buildkite/test-splitter-client-release/GH_TOKEN
      - docker-compose#v4.14.0:
          config: .buildkite/docker-compose.yml
          cli-version: 2
          run: release
          mount-checkout: true
          mount-ssh-agent: true
          mount-buildkite-agent: true
          env:
            - ARTIFACTS_BUILD_ID
            - GH_TOKEN
