steps:
  - name: ":cook: Prepare release"
    plugins:
      - docker#v5.11.0:
          image: ghcr.io/caarlos0/svu:v2.1.0
          entrypoint: ""
          command: [".buildkite/steps/prepare-release.sh"]
          mount-buildkite-agent: true
  
  - wait 

  - name: ":rocket: Release"
    artifact_paths: "dist/**/*"
    plugins:
      - aws-assume-role-with-web-identity:
          role-arn: arn:aws:iam::445615400570:role/pipeline-buildkite-test-splitter-client-release
      - aws-ssm#v1.0.0:
          parameters:
            GITHUB_TOKEN: /pipelines/buildkite/test-splitter-client-release/GH_TOKEN
            DOCKERHUB_USER: /pipelines/buildkite/test-splitter-client-release/dockerhub-user
            DOCKERHUB_PASSWORD: /pipelines/buildkite/test-splitter-client-release/dockerhub-password
      - docker#v5.11.0:
          image: goreleaser/goreleaser:v2.1.0
          entrypoint: ""
          command: [".buildkite/steps/release.sh"]
          mount-buildkite-agent: true
          volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
          environment:
            - GITHUB_TOKEN
            - DOCKERHUB_USER
            - DOCKERHUB_PASSWORD
