steps:
  - name: ":octocat: :rocket: Create Github Release"
    command: ".buildkite/steps/github-release.sh"
    plugins:
      - docker-compose#v4.14.0:
          config: .buildkite/docker-compose.yml
          cli-version: 2
          run: release
          mount-checkout: true