steps:
  - name: ":go::robot_face: Check Code Committed"
    key: check-code-committed
    command: .buildkite/steps/check-code-committed.sh
    plugins:
      - docker-compose#v4.14.0:
          config: .buildkite/docker-compose.yml
          cli-version: 2
          run: build

  - name: ":go: Tests with race detector"
    key: tests
    command: ".buildkite/steps/tests.sh -race"
    artifact_paths: cover.{html,out}
    plugins:
      - docker-compose#v4.14.0:
          config: .buildkite/docker-compose.yml
          cli-version: 2
          run: build
      - test-collector#v1.2.0:
          files: "junit-*.xml"
          format: "junit"

  - wait

  - group: ":hammer_and_wrench: Binary builds"
    steps:
    - name: ":{{matrix.os}}: Build {{matrix.os}} {{matrix.arch}} binary"
      command: ".buildkite/steps/build-binary.sh {{matrix.os}} {{matrix.arch}}"
      key: build-binary
      artifact_paths: "pkg/*"
      plugins:
        docker-compose#v4.14.0:
          config: .buildkite/docker-compose.yml
          cli-version: 2
          run: build
      matrix:
        setup:
          os:
            - darwin
            - linux
          arch:
            - amd64
            - arm64
    
  - group: "rspec"
    key: rspec
    depends_on: 
      - build-binary
    steps: 
    - name: "Run rspec"
      command: .buildkite/steps/install-binary.sh
      plugins:
        docker-compose#v4.14.0:
          config: .buildkite/docker-compose.yml
          cli-version: 2
          run: e2e
          pull-retries: 2
          mount-checkout: true
          mount-buildkite-agent: true
      env:
        BUILDKITE_SPLITTER_BASE_URL: https://buildkite.com
        BUILDKITE_SUITE_TOKEN: ${BUILDKITE_ANALYTICS_TOKEN}
      parallelism: 3
    
    - name: "Run rspec (fallback mode due to 500)"
      command: .buildkite/steps/install-binary.sh
      plugins:
        docker-compose#v4.14.0:
          config: .buildkite/docker-compose.yml
          cli-version: 2
          run: e2e
          pull-retries: 2
          mount-checkout: true
          mount-buildkite-agent: true
      env:
        BUILDKITE_SPLITTER_BASE_URL: https://build.kite.com
        BUILDKITE_SUITE_TOKEN: ${BUILDKITE_ANALYTICS_TOKEN}
      parallelism: 3

    - name: "Run rspec (fallback mode due to error plan)"
      command: .buildkite/steps/install-binary.sh
      plugins:
        docker-compose#v4.14.0:
          config: .buildkite/docker-compose.yml
          cli-version: 2
          run: e2e
          pull-retries: 2
          mount-checkout: true
          mount-buildkite-agent: true
      env:
        BUILDKITE_SPLITTER_BASE_URL: https://buildkite.com
        BUILDKITE_SUITE_TOKEN: ${BUILDKITE_ANALYTICS_TOKEN}
        ERROR_PLAN: true
      parallelism: 3