steps:
  - name: ":go::robot_face: Check Code Committed"
    key: check-code-committed
    command: .buildkite/steps/check-code-committed.sh
    plugins:
      - docker-compose#v4.14.0:
          config: .buildkite/docker-compose.yml
          cli-version: 2
          run: build

  - name: ":go: Tests with race detector"
    key: tests
    command: ".buildkite/steps/tests.sh -race"
    artifact_paths:
      - cover.{html,out}
      - internal/api/pacts/*
    plugins:
      - docker-compose#v4.14.0:
          config: .buildkite/docker-compose.yml
          cli-version: 2
          run: build

  - wait

  - group: ":hammer_and_wrench: Build Binaries"
    steps:
    - name: ":{{matrix.os}}: Build {{matrix.os}} {{matrix.arch}} binary"
      command: ".buildkite/steps/build-binary.sh {{matrix.os}} {{matrix.arch}}"
      key: build-binaries
      artifact_paths: "pkg/*"
      plugins:
        docker-compose#v4.14.0:
          config: .buildkite/docker-compose.yml
          cli-version: 2
          run: build
      matrix:
        setup:
          os:
            - darwin
            - linux
          arch:
            - amd64
            - arm64
