// Code generated by "stringer -type=Runner"; DO NOT EDIT.

package api

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Rspec-0]
	_ = x[Jest-1]
	_ = x[Cypress-2]
}

const _Runner_name = "RspecJestCypress"

var _Runner_index = [...]uint8{0, 5, 9, 16}

func (i Runner) String() string {
	if i < 0 || i >= Runner(len(_Runner_index)-1) {
		return "Runner(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Runner_name[_Runner_index[i]:_Runner_index[i+1]]
}
