package runner

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"slices"
	"strings"

	"github.com/buildkite/test-engine-client/v2/internal/debug"
	"github.com/buildkite/test-engine-client/v2/internal/plan"
	"github.com/kballard/go-shellquote"
)

// Vitest is a first-class runner for the Vitest test framework.
//
// Vitest's JSON reporter is Jest-compatible, so the result file is parsed using
// the shared JestReport types. The main differences from the Jest runner are
// the default test/retry commands and the result format identifier.
type Vitest struct {
	RunnerConfig
}

func NewVitest(v RunnerConfig) Vitest {
	if v.TestCommand == "" {
		v.TestCommand = "npx vitest run {{testExamples}} --reporter=default --reporter=json --outputFile {{resultPath}}"
	}

	if v.TestFilePattern == "" {
		v.TestFilePattern = "**/{__tests__/**/*,*.spec,*.test}.{ts,js,tsx,jsx}"
	}

	if v.RetryTestCommand == "" {
		v.RetryTestCommand = "npx vitest run --testNamePattern '{{testNamePattern}}' --reporter=default --reporter=json --outputFile {{resultPath}}"
	}

	return Vitest{
		RunnerConfig: v,
	}
}

func (v Vitest) SupportedFeatures() SupportedFeatures {
	return SupportedFeatures{
		SplitByFile:     true,
		SplitByExample:  false,
		FilterTestFiles: true,
		FilterTestByTag: false,
		AutoRetry:       true,
		Mute:            true,
		Skip:            false,
	}
}

func (v Vitest) Name() string {
	return "Vitest"
}

func (v Vitest) ResultFormat() string {
	return "jest-json"
}

// GetFiles returns an array of file names using the discovery pattern.
func (v Vitest) GetFiles() ([]string, error) {
	debug.Println("Discovering test files with include pattern:", v.TestFilePattern, "exclude pattern:", v.TestFileExcludePattern)
	files, err := discoverTestFiles(v.TestFilePattern, v.TestFileExcludePattern)
	debug.Println("Discovered", len(files), "files")

	if err != nil {
		return nil, err
	}

	if len(files) == 0 {
		return nil, fmt.Errorf("no files found with pattern %q and exclude pattern %q", v.TestFilePattern, v.TestFileExcludePattern)
	}

	return files, nil
}

func (v Vitest) Run(result *RunResult, testCases []plan.TestCase, retry bool) error {
	cmd, err := buildCommand(v, testCases, retry)
	if err != nil {
		return err
	}

	cmdErr := runAndForwardSignal(cmd)

	// Vitest exits with a non-zero status code when there are test failures,
	// so we should always attempt to parse the report even if the command returns an error.
	report, parseErr := ParseJestReport(v.ResultPath)
	if parseErr != nil {
		fmt.Printf("Buildkite Test Engine Client: Failed to read Vitest output, tests will not be retried: %v\n", parseErr)
		// We don't want to fail the build if we fail to parse the report,
		// therefore we return the command error (which can be nil), instead of the parse error.
		return cmdErr
	}

	retryTestLookup := map[string]bool{}
	if retry {
		for _, testCase := range testCases {
			retryTestLookup[testIdentifier(testCase)] = true
		}
	}

	for _, testResult := range report.TestResults {
		// A TestResult with status "failed" but no AssertionResults indicates a
		// file-level runtime error (e.g. an import that throws).
		if testResult.Status == "failed" && len(testResult.AssertionResults) == 0 {
			result.error = fmt.Errorf("Vitest failed with runtime error test suites")
		}

		for _, example := range testResult.AssertionResults {
			var status TestStatus
			switch example.Status {
			case "failed":
				status = TestStatusFailed
			case "passed":
				status = TestStatusPassed
			case "pending":
				status = TestStatusSkipped
			// Vitest reports skipped tests (it.skip / it.todo) with status
			// "skipped", whereas Jest uses "pending". Handle both.
			case "skipped":
				status = TestStatusSkipped
			case "todo":
				status = TestStatusSkipped
			default:
				status = TestStatusUnknown
			}

			workDir, err := os.Getwd()
			if err != nil {
				return fmt.Errorf("failed to get current working directory: %v", err)
			}
			testPath, err := filepath.Rel(workDir, testResult.FileName)
			if err != nil {
				return fmt.Errorf("failed to get relative path of test file: %v", err)
			}

			// The scope and name has to match the scope generated by the Buildkite
			// test collector's Vitest reporter so splitting and collection line up
			// on the same test identities.
			testCase := plan.TestCase{
				Name:  example.Title,
				Scope: strings.Join(example.AncestorTitles, " "),
				Path:  testPath,
			}
			if retry && status == TestStatusSkipped && !retryTestLookup[testIdentifier(testCase)] {
				continue
			}

			result.RecordTestResult(testCase, status)
		}
	}

	return cmdErr
}

func (v Vitest) CommandNameAndArgs(testCases []plan.TestCase, retry bool) (string, []string, error) {
	cmd := v.TestCommand
	if retry {
		cmd = v.RetryTestCommand
	}

	words, err := shellquote.Split(cmd)
	if err != nil {
		return "", []string{}, err
	}

	testPaths := pathsFromTestCases(testCases)
	slices.Sort(testPaths)
	testPaths = slices.Compact(testPaths)

	if retry {
		idx := slices.Index(words, "{{testNamePattern}}")
		if idx < 0 {
			return "", []string{}, fmt.Errorf("couldn't find '{{testNamePattern}}' sentinel in retry command")
		}

		escapedTestCases := make([]string, len(testCases))
		for i, testCase := range testCases {
			fullName := testCase.Name
			if testCase.Scope != "" {
				fullName = fmt.Sprintf("%s %s", testCase.Scope, testCase.Name)
			}
			escapedTestCases[i] = regexp.QuoteMeta(fullName)
		}

		testNamePattern := fmt.Sprintf("(%s)", strings.Join(escapedTestCases, "|"))
		words = slices.Replace(words, idx, idx+1, testNamePattern)

		testExamplesIdx := slices.Index(words, "{{testExamples}}")
		if testExamplesIdx >= 0 {
			words = slices.Replace(words, testExamplesIdx, testExamplesIdx+1, testPaths...)
		}
	} else {
		idx := slices.Index(words, "{{testExamples}}")
		if idx < 0 {
			words = append(words, testPaths...)
		} else {
			words = slices.Replace(words, idx, idx+1, testPaths...)
		}
	}

	outputIdx := slices.Index(words, "{{resultPath}}")
	if outputIdx < 0 {
		return "", []string{}, fmt.Errorf("couldn't find '{{resultPath}}' sentinel in command, exiting")
	}
	words = slices.Replace(words, outputIdx, outputIdx+1, v.ResultPath)

	return words[0], words[1:], nil
}

func (v Vitest) GetExamples(files []string) ([]plan.TestCase, error) {
	return nil, fmt.Errorf("not supported in Vitest")
}
