#!/bin/bash

if [ "$1" != "oidc" ] ; then
  echo "mock-buildkite-agent got unexpected \$1: $1" >&2
  exit 1
fi

if [ "$2" != "request-token" ] ; then
  echo "mock-buildkite-agent got unexpected \$2: $2" >&2
  exit 1
fi

if [[ "$*" == *test_queue* ]] ; then
  if [[ "$*" != *"--claim build_id"* ]] ; then
    echo "mock-buildkite-agent did not get build_id claim request" >&2
    exit 1
  fi

  if [[ "$*" != *"--claim organization_id"* ]] ; then
    echo "mock-buildkite-agent did not get organization_id claim request" >&2
    exit 1
  fi
fi

echo "mocktoken"
